sudo: false
language: rust
cache: cargo

# Run builds for all the trains (and more).
# Remember to update the numbers in travis.sh too.
rust:
  - stable
  - nightly
  - beta

matrix:
  include:
    - rust: nightly
      env: CLIPPY=true
